language: php
php:
  - '7.2'

cache:
  directories:
    - $HOME/.composer/cache

env:
 - PHPUNIT_VERSION=8.0.* TESTBENCH_VERSION=4.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update
  - travis_retry composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
